channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyter=1.0.0
  - pip=23.2.1
  - pre-commit=3.5.0
  - python=3.12.0
  - ruff=0.4.4
  - click=8.1.7
  - h5py=3.11.0
  - imageio=2.34.1
  - matplotlib=3.8.4
  - nd2=0.10.1
  - numcodecs=0.12.1
  - numpy=2.0.0
  - opencv=4.9.0
  - pillow=10.3.0
  - pims=0.6.1
  - py-opencv=4.9.0
  - scikit-image=0.24.0
  - tifffile=2024.7.24
  - tqdm=4.66.4
  - zarr=2.18.2
  - bioconductor-rhdf5=2.46.1
  - r-irkernel=1.3.2
  - r-tidyverse=2.0.0
